#!/usr/bin/env python3
"""Fetch the full advisory list under openclaw/openclaw and write a manifest
file in the same format as OpenClawBench's manifest.json.

This script is provided for two cases:
  1. You want to update OpenClawBench with advisories disclosed after the
     paper's cutoff (2026-04-01).
  2. You want to reproduce the manifest from scratch.

For each advisory we join against OSV.dev to recover the fix-commit SHA
(the public GitHub Security Advisories API does not return fix commits).

Usage:
    python fetch_advisories.py \
        --output ./manifest_new.json \
        --since 2026-04-01      # optional, default fetches all
"""
import argparse, json, os, re, sys, time, urllib.request, urllib.error
from pathlib import Path

OWNER_REPO = 'openclaw/openclaw'
COMMIT_RE = re.compile(r'github\.com/openclaw/openclaw/commit/([0-9a-f]{7,40})')


def gh(url, token=None, retries=3):
    headers = {'Accept': 'application/vnd.github+json',
               'X-GitHub-Api-Version': '2022-11-28',
               'User-Agent': 'openclawbench-fetcher'}
    if token:
        headers['Authorization'] = f'Bearer {token}'
    for i in range(retries):
        try:
            req = urllib.request.Request(url, headers=headers)
            resp = urllib.request.urlopen(req, timeout=30)
            return json.loads(resp.read()), resp.headers
        except urllib.error.HTTPError as e:
            if e.code == 404:
                return None, None
            if e.code in (403, 429):
                wait = 30 * (i + 1)
                print(f'  rate-limited, sleeping {wait}s', file=sys.stderr)
                time.sleep(wait)
                continue
            raise


def osv(gid):
    try:
        req = urllib.request.Request(
            f'https://api.osv.dev/v1/vulns/{gid}',
            headers={'User-Agent': 'openclawbench-fetcher'})
        return json.loads(urllib.request.urlopen(req, timeout=15).read())
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return None
        raise


def list_advisories(token=None):
    """Paginate all published advisories via Link-header cursor."""
    url = f'https://api.github.com/repos/{OWNER_REPO}/security-advisories?per_page=100'
    out = []
    while url:
        page, headers = gh(url, token)
        if not page:
            break
        out.extend(page)
        link = headers.get('Link', '') if headers else ''
        m = re.search(r'<([^>]+)>;\s*rel="next"', link)
        url = m.group(1) if m else None
    return out


def classify_file(path):
    if re.search(r'(\.test\.(t|j)sx?$|\.spec\.(t|j)sx?$|/__tests__/|/tests?/)', path, re.I):
        return 'test'
    if re.search(r'\.(md|mdx|rst|adoc|txt)$', path, re.I):
        return 'doc'
    return 'vuln'


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--output', default='./manifest_new.json')
    ap.add_argument('--since', help='Filter to advisories published on or after this date (YYYY-MM-DD).')
    ap.add_argument('--token', default=os.environ.get('GITHUB_TOKEN'),
                    help='GitHub token (also reads $GITHUB_TOKEN).')
    args = ap.parse_args()

    print('Listing advisories from GitHub ...')
    advs = list_advisories(args.token)
    print(f'  found {len(advs)} published advisories')
    if args.since:
        advs = [a for a in advs if a.get('published_at', '') >= args.since]
        print(f'  {len(advs)} after --since {args.since}')

    manifest = {'description': 'OpenClawBench manifest (regenerated by fetch_advisories.py)',
                'advisories': []}
    stats = {'with_fix_commit': 0, 'no_osv': 0, 'no_commit_in_osv': 0}
    for i, a in enumerate(advs, 1):
        gid = a['ghsa_id']
        # Find fix commit via OSV
        fix_sha = parent_sha = None
        vfiles = fix_files = test_files = []
        o = osv(gid)
        if not o:
            stats['no_osv'] += 1
        else:
            shas = []
            for r in o.get('references', []):
                m = COMMIT_RE.search(r.get('url', ''))
                if m:
                    shas.append(m.group(1))
            if not shas:
                stats['no_commit_in_osv'] += 1
            else:
                fix_sha = shas[0]
                commit, _ = gh(f'https://api.github.com/repos/{OWNER_REPO}/commits/{fix_sha}',
                               args.token)
                if commit:
                    parents = commit.get('parents') or []
                    parent_sha = parents[0]['sha'] if parents else None
                    for f in (commit.get('files') or []):
                        p = f.get('filename', '')
                        kind = classify_file(p)
                        if kind == 'vuln':
                            vfiles.append(p); fix_files.append(p)
                        elif kind == 'test':
                            test_files.append(p)
                    stats['with_fix_commit'] += 1

        entry = {
            'ghsa_id': gid,
            'cve_id': a.get('cve_id'),
            'severity': a.get('severity'),
            'cwe_ids': [c.get('cwe_id') for c in a.get('cwes', [])],
            'published_at': a.get('published_at'),
            'summary': a.get('summary', ''),
            'fix_sha': fix_sha,
            'parent_sha': parent_sha,
            'vulnerable_files': vfiles,
        }
        manifest['advisories'].append(entry)
        if i % 25 == 0 or i == len(advs):
            print(f'  [{i}/{len(advs)}] {stats}')

    with open(args.output, 'w') as f:
        json.dump(manifest, f, indent=2)
    print(f'\nDone. Wrote {len(manifest["advisories"])} entries to {args.output}')
    print(f'Stats: {stats}')


if __name__ == '__main__':
    main()
